/// <amd-module name="@the-gear/sample-rollup-server-simple/src/schema.graphql" />
export declare const sha384Hash: string;
/*********************************** THIS IS AUTOGENERATED FILE ***********************************/
export declare const src: string;
/*********************************** THIS IS AUTOGENERATED FILE ***********************************/
export declare const source: import('graphql').Source;
/*********************************** THIS IS AUTOGENERATED FILE ***********************************/
export declare const documentNode: any;
/*********************************** THIS IS AUTOGENERATED FILE ***********************************/
export declare const documentAst: import('graphql').DocumentNode;
/*********************************** THIS IS AUTOGENERATED FILE ***********************************/
/**
 * Type config for object Query
 *
 * Root query type 3
 */
export declare const QueryTypeConfig: import('graphql/type').GraphQLObjectTypeConfig;
export declare const schema: any;
export default schema;
